### ISSUE TITLE
hide social info icon if field is blank

### ISSUE THREAD

**Issue by mikemaddem** [NFM-Studios/project-olly#119]

**Comment by tkenney124** [comment]
Changes made today to base.html


{% if SocialInfo.twitterprofile != None %}
            <a href="{{ SocialInfo.twitterprofile }}"><i class="fab fa-twitter-square"></i></a>
            {% endif %}

            {% if SocialInfo.facebookpage != None %}
            <a href="{{ SocialInfo.facebookpage }}"><i class="fab fa-facebook-square"></i></a>
            {% endif %}

            {% if SocialInfo.youtubechannel != None %}
            <a href="{{ SocialInfo.youtubechannel }}"><i class="fab fa-youtube-square"></i></a>
            {% endif %}

            {% if SocialInfo.twitchchannel != None %}
            <a href="{{ SocialInfo.twitchchannel }}"><i class="fab fa-twitch"></i></a>
            {% endif %}

            {% if SocialInfo.discord != None %}
            <a href="{{ SocialInfo.discord }}"><i class="fab fa-discord"></i></a>
            {% endif %}
