### ISSUE TITLE
"num" instead of "pk" in teams/urls

### ISSUE THREAD

**Issue by techlover1** [NFM-Studios/project-olly#42]

**Comment by mikemaddem** [comment]
More info? Description?

**Comment by techlover1** [comment]
https://github.com/NFM-Studios/project-olly/blob/ea5b75f3517d5cf001b82af8123c5af831c8c753/teams/urls.py#L13 uses <int:num> instead of our standard <int:pk>
I'm not sure of the ramifications of changing this, so thorough testing will be required

**Comment by mikemaddem** [comment]
it's simply naming the int pk value num instead of pk. not a bug or anything to worry about.

**Comment by mikemaddem** [comment]
poses no functionality difference, closed
