### ISSUE TITLE
Stock template bracket styling is missing

### ISSUE THREAD

**Issue by mikemaddem** [NFM-Studios/project-olly#46]
Somehow amidst the static file consolidation the css styling for brackets was removed and the styling for brackets are now non functional.

**Comment by techlover1** [comment]
Just took a brief look, I don't see where it was functional before I consolidated the files.
We may want to take this opportunity to re-write and optimize the brackets

**Comment by mikemaddem** [comment]
Fixed on develop branch - waiting to be merged
